Repository SciTools/iris-grib, pull requests merged in 2019-11, with the labels that each got.

#148 Fix to read grib files obeying 'resolutionAndComponentFlags'
  iris_grib/_load_convert.py
  iris_grib/tests/unit/load_convert/test_calculate_increment.py
  iris_grib/tests/unit/load_convert/test_grid_definition_template_0_and_1.py
  iris_grib/tests/unit/load_convert/test_grid_definition_template_40.py
Labels: SemVer: Minor, Type: Enhancement

#166 Drop Python 2 Testing
  .travis.yml
  environment.yml
Labels: SemVer: Major, Type: Infrastructure

#169 0.14.x mergeback onto master
  iris_grib/__init__.py
  iris_grib/message.py
Labels: Type: Infrastructure
